/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
//package bank;

import java.util.Date;

/**
 *
 * @author DELL
 */
public class Custumer extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame
     */
    public Custumer() {
        initComponents();

        Date date = new Date();
        dateChooser_withdepCustomer.setDate(date);
        dateChooser_loan.setDate(date);
        dateChooser_transform.setDate(date);
        name_ofanother_bank_transform_lable.setVisible(false);
        name_ofanother_bank_transform_textField.setVisible(false);
        todate_visit_dateChooser.setVisible(false);
        fromdate_visit_dateChooser.setVisible(false);
        todate_visit_lable.setVisible(false);
        fromdate_visit_lable.setVisible(false);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        with_depo_radio_group = new javax.swing.ButtonGroup();
        name_of_the_bank_radio_group = new javax.swing.ButtonGroup();
        visit_radio_group = new javax.swing.ButtonGroup();
        withDep_cutomer_tabbed = new javax.swing.JTabbedPane();
        withdraw_depo_panel = new javax.swing.JPanel();
        idcustomer_withdepCutomer_lable = new javax.swing.JLabel();
        idcustomer_withdepCutomer_textfield = new javax.swing.JTextField();
        pass_withdepCustomer_lable = new javax.swing.JLabel();
        widdepo_withdepCustomer_label = new javax.swing.JLabel();
        newmoney_withdepCustomer_label = new javax.swing.JLabel();
        withdepo_withdepCustomer_textfield = new javax.swing.JTextField();
        newmoney_withdepCustomer_lable = new javax.swing.JLabel();
        money_withdepCustomer_label = new javax.swing.JLabel();
        money_withdepCustomer_lable = new javax.swing.JLabel();
        withd_withdepCustomer_radio = new javax.swing.JRadioButton();
        withdep_withdepCustomer_button = new javax.swing.JButton();
        depo_withdepCustomer_radio = new javax.swing.JRadioButton();
        date_withdepCustomer_lable = new javax.swing.JLabel();
        dateChooser_withdepCustomer = new com.toedter.calendar.JDateChooser();
        pass_withdepCustomer_Password = new javax.swing.JPasswordField();
        loan_panel = new javax.swing.JPanel();
        idcutomer_loan_lable = new javax.swing.JLabel();
        id_loan_textfield = new javax.swing.JTextField();
        pass_loan_lable = new javax.swing.JLabel();
        pass_loan_Password = new javax.swing.JPasswordField();
        idG1_loan_lable = new javax.swing.JLabel();
        idG1_loan_textfield = new javax.swing.JTextField();
        money_loan_lable = new javax.swing.JLabel();
        idG2_loan_lable = new javax.swing.JLabel();
        idG3_loan_lable = new javax.swing.JLabel();
        idG2_loan_textfield = new javax.swing.JTextField();
        idG3_loan_textfield = new javax.swing.JTextField();
        money_loan_textfield = new javax.swing.JTextField();
        dateChooser_loan = new com.toedter.calendar.JDateChooser();
        data_loan_lable = new javax.swing.JLabel();
        period_loan_lable = new javax.swing.JLabel();
        period_loan_textField = new javax.swing.JTextField();
        period_loan_comboBox = new javax.swing.JComboBox<>();
        tansform_panel = new javax.swing.JPanel();
        idcutomer_transform_lable = new javax.swing.JLabel();
        idcustomer_transform_textfield = new javax.swing.JTextField();
        idtransportor_transform_lable = new javax.swing.JLabel();
        idtransportor_transform_textfield1 = new javax.swing.JTextField();
        money_transform_lable = new javax.swing.JLabel();
        money_transform_textfield = new javax.swing.JTextField();
        data_transform_lable = new javax.swing.JLabel();
        dateChooser_transform = new com.toedter.calendar.JDateChooser();
        idcutomer_transform_lable1 = new javax.swing.JLabel();
        same_bank_tranform_radioButton = new javax.swing.JRadioButton();
        another_bank_tranform_radioButton = new javax.swing.JRadioButton();
        name_ofanother_bank_transform_lable = new javax.swing.JLabel();
        name_ofanother_bank_transform_textField = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        idcustomer_visit_lable = new javax.swing.JLabel();
        idcustomer_visit_textfield = new javax.swing.JTextField();
        pass_withdepCustomer_lable1 = new javax.swing.JLabel();
        pass_withdepCustomer_Password1 = new javax.swing.JPasswordField();
        withdrow_deposit_visit_radio = new javax.swing.JRadioButton();
        loans_payment_radio = new javax.swing.JRadioButton();
        total_money_visit_radio = new javax.swing.JRadioButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        with_depo_visit_table = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        loans_payment_visit_table = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        total_money_visit_table1 = new javax.swing.JTable();
        fromdate_visit_lable = new javax.swing.JLabel();
        fromdate_visit_dateChooser = new com.toedter.calendar.JDateChooser();
        todate_visit_lable = new javax.swing.JLabel();
        todate_visit_dateChooser = new com.toedter.calendar.JDateChooser();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        withDep_cutomer_tabbed.setFont(new java.awt.Font("Swis721 LtCn BT", 1, 12)); // NOI18N

        idcustomer_withdepCutomer_lable.setFont(new java.awt.Font("Swis721 LtCn BT", 1, 15)); // NOI18N
        idcustomer_withdepCutomer_lable.setText("ID customer :");

        idcustomer_withdepCutomer_textfield.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                idcustomer_withdepCutomer_textfieldActionPerformed(evt);
            }
        });

        pass_withdepCustomer_lable.setFont(new java.awt.Font("Swis721 LtCn BT", 1, 15)); // NOI18N
        pass_withdepCustomer_lable.setText("Password :");

        widdepo_withdepCustomer_label.setFont(new java.awt.Font("Swis721 LtCn BT", 1, 14)); // NOI18N
        widdepo_withdepCustomer_label.setText("Money to withdraw or deposit :");

        newmoney_withdepCustomer_label.setFont(new java.awt.Font("Swis721 LtCn BT", 1, 15)); // NOI18N
        newmoney_withdepCustomer_label.setText("New Total Money :");

        withdepo_withdepCustomer_textfield.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                withdepo_withdepCustomer_textfieldActionPerformed(evt);
            }
        });

        newmoney_withdepCustomer_lable.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        money_withdepCustomer_label.setFont(new java.awt.Font("Swis721 LtCn BT", 1, 15)); // NOI18N
        money_withdepCustomer_label.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        money_withdepCustomer_label.setText("Total money");
        money_withdepCustomer_label.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        money_withdepCustomer_lable.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        with_depo_radio_group.add(withd_withdepCustomer_radio);
        withd_withdepCustomer_radio.setFont(new java.awt.Font("Swis721 LtCn BT", 1, 14)); // NOI18N
        withd_withdepCustomer_radio.setText("Withdraw");
        withd_withdepCustomer_radio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                withd_withdepCustomer_radioActionPerformed(evt);
            }
        });

        withdep_withdepCustomer_button.setFont(new java.awt.Font("Swis721 LtCn BT", 1, 15)); // NOI18N
        withdep_withdepCustomer_button.setText("Enter");
        withdep_withdepCustomer_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                withdep_withdepCustomer_buttonActionPerformed(evt);
            }
        });

        with_depo_radio_group.add(depo_withdepCustomer_radio);
        depo_withdepCustomer_radio.setFont(new java.awt.Font("Swis721 LtCn BT", 1, 14)); // NOI18N
        depo_withdepCustomer_radio.setText("Deposit");

        date_withdepCustomer_lable.setFont(new java.awt.Font("Swis721 LtCn BT", 1, 15)); // NOI18N
        date_withdepCustomer_lable.setText("Date of operation :");

        pass_withdepCustomer_Password.setFont(new java.awt.Font("Swis721 LtCn BT", 0, 14)); // NOI18N
        pass_withdepCustomer_Password.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pass_withdepCustomer_PasswordActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout withdraw_depo_panelLayout = new javax.swing.GroupLayout(withdraw_depo_panel);
        withdraw_depo_panel.setLayout(withdraw_depo_panelLayout);
        withdraw_depo_panelLayout.setHorizontalGroup(
            withdraw_depo_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(withdraw_depo_panelLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(withdraw_depo_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(withdraw_depo_panelLayout.createSequentialGroup()
                        .addGroup(withdraw_depo_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(date_withdepCustomer_lable, javax.swing.GroupLayout.DEFAULT_SIZE, 140, Short.MAX_VALUE)
                            .addComponent(idcustomer_withdepCutomer_lable, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(pass_withdepCustomer_lable, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(withdraw_depo_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(withdraw_depo_panelLayout.createSequentialGroup()
                                .addGap(200, 200, 200)
                                .addGroup(withdraw_depo_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(money_withdepCustomer_lable, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(money_withdepCustomer_label, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(withdraw_depo_panelLayout.createSequentialGroup()
                                .addGroup(withdraw_depo_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(withdraw_depo_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(idcustomer_withdepCutomer_textfield, javax.swing.GroupLayout.DEFAULT_SIZE, 169, Short.MAX_VALUE)
                                        .addComponent(dateChooser_withdepCustomer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addComponent(pass_withdepCustomer_Password, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addContainerGap(191, Short.MAX_VALUE))))
                    .addGroup(withdraw_depo_panelLayout.createSequentialGroup()
                        .addGroup(withdraw_depo_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(widdepo_withdepCustomer_label, javax.swing.GroupLayout.DEFAULT_SIZE, 185, Short.MAX_VALUE)
                            .addComponent(newmoney_withdepCustomer_label, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGroup(withdraw_depo_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(withdraw_depo_panelLayout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(newmoney_withdepCustomer_lable, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, withdraw_depo_panelLayout.createSequentialGroup()
                                .addGap(19, 19, 19)
                                .addComponent(withdepo_withdepCustomer_textfield, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addGroup(withdraw_depo_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(depo_withdepCustomer_radio, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(withd_withdepCustomer_radio))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(withdep_withdepCustomer_button, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(12, 12, 12))))))
        );
        withdraw_depo_panelLayout.setVerticalGroup(
            withdraw_depo_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(withdraw_depo_panelLayout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addGroup(withdraw_depo_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(idcustomer_withdepCutomer_lable, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(idcustomer_withdepCutomer_textfield, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(withdraw_depo_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(pass_withdepCustomer_lable, javax.swing.GroupLayout.DEFAULT_SIZE, 34, Short.MAX_VALUE)
                    .addComponent(money_withdepCustomer_label, javax.swing.GroupLayout.DEFAULT_SIZE, 34, Short.MAX_VALUE)
                    .addComponent(pass_withdepCustomer_Password))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, 25, Short.MAX_VALUE)
                .addComponent(money_withdepCustomer_lable, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22)
                .addGroup(withdraw_depo_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(date_withdepCustomer_lable, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(dateChooser_withdepCustomer, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(19, 19, 19)
                .addGroup(withdraw_depo_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(withdraw_depo_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(withdraw_depo_panelLayout.createSequentialGroup()
                            .addComponent(withd_withdepCustomer_radio, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(depo_withdepCustomer_radio, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(withdep_withdepCustomer_button, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(withdraw_depo_panelLayout.createSequentialGroup()
                        .addGroup(withdraw_depo_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(widdepo_withdepCustomer_label, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(withdepo_withdepCustomer_textfield, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(27, 27, 27)
                        .addGroup(withdraw_depo_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(newmoney_withdepCustomer_label, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(newmoney_withdepCustomer_lable, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(46, 46, 46))
        );

        withDep_cutomer_tabbed.addTab("  Withdraw or Deposit   ", withdraw_depo_panel);

        idcutomer_loan_lable.setFont(new java.awt.Font("Swis721 LtCn BT", 1, 15)); // NOI18N
        idcutomer_loan_lable.setText("ID customer :");

        id_loan_textfield.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                id_loan_textfieldActionPerformed(evt);
            }
        });

        pass_loan_lable.setFont(new java.awt.Font("Swis721 LtCn BT", 1, 15)); // NOI18N
        pass_loan_lable.setText("Password :");

        pass_loan_Password.setFont(new java.awt.Font("Swis721 LtCn BT", 0, 14)); // NOI18N
        pass_loan_Password.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pass_loan_PasswordActionPerformed(evt);
            }
        });

        idG1_loan_lable.setFont(new java.awt.Font("Swis721 LtCn BT", 1, 14)); // NOI18N
        idG1_loan_lable.setText("ID Guarantor1 :");

        idG1_loan_textfield.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                idG1_loan_textfieldActionPerformed(evt);
            }
        });

        money_loan_lable.setFont(new java.awt.Font("Swis721 LtCn BT", 1, 15)); // NOI18N
        money_loan_lable.setText("Money :");

        idG2_loan_lable.setFont(new java.awt.Font("Swis721 LtCn BT", 1, 14)); // NOI18N
        idG2_loan_lable.setText("ID Guarantor2 :");

        idG3_loan_lable.setFont(new java.awt.Font("Swis721 LtCn BT", 1, 14)); // NOI18N
        idG3_loan_lable.setText("ID Guarantor3 :");

        idG2_loan_textfield.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                idG2_loan_textfieldActionPerformed(evt);
            }
        });

        idG3_loan_textfield.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                idG3_loan_textfieldActionPerformed(evt);
            }
        });

        money_loan_textfield.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                money_loan_textfieldActionPerformed(evt);
            }
        });

        data_loan_lable.setFont(new java.awt.Font("Swis721 LtCn BT", 1, 15)); // NOI18N
        data_loan_lable.setText("The date of the loan :");

        period_loan_lable.setFont(new java.awt.Font("Swis721 LtCn BT", 1, 15)); // NOI18N
        period_loan_lable.setText("The period of the loan :");

        period_loan_textField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                period_loan_textFieldActionPerformed(evt);
            }
        });

        period_loan_comboBox.setFont(new java.awt.Font("Swis721 LtCn BT", 0, 18)); // NOI18N
        period_loan_comboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Year", "Month" }));
        period_loan_comboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                period_loan_comboBoxActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout loan_panelLayout = new javax.swing.GroupLayout(loan_panel);
        loan_panel.setLayout(loan_panelLayout);
        loan_panelLayout.setHorizontalGroup(
            loan_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(loan_panelLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(loan_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(loan_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(data_loan_lable, javax.swing.GroupLayout.DEFAULT_SIZE, 147, Short.MAX_VALUE)
                        .addComponent(idG3_loan_lable, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(pass_loan_lable, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(idG1_loan_lable, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(idG2_loan_lable, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(idcutomer_loan_lable, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(money_loan_lable, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(period_loan_lable))
                .addGap(27, 27, 27)
                .addGroup(loan_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(loan_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(id_loan_textfield, javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(dateChooser_loan, javax.swing.GroupLayout.DEFAULT_SIZE, 168, Short.MAX_VALUE)
                        .addComponent(pass_loan_Password)
                        .addComponent(idG1_loan_textfield, javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(idG2_loan_textfield, javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(idG3_loan_textfield, javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(money_loan_textfield))
                    .addGroup(loan_panelLayout.createSequentialGroup()
                        .addComponent(period_loan_textField, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(period_loan_comboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(175, Short.MAX_VALUE))
        );
        loan_panelLayout.setVerticalGroup(
            loan_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(loan_panelLayout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(loan_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(idcutomer_loan_lable, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(id_loan_textfield, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(loan_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(pass_loan_lable, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pass_loan_Password, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(loan_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(idG1_loan_lable, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(idG1_loan_textfield, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(loan_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(idG2_loan_lable, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(idG2_loan_textfield, javax.swing.GroupLayout.DEFAULT_SIZE, 27, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(loan_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(idG3_loan_textfield, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(idG3_loan_lable, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(loan_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(money_loan_textfield, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(money_loan_lable, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(loan_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(period_loan_comboBox, javax.swing.GroupLayout.DEFAULT_SIZE, 37, Short.MAX_VALUE)
                    .addComponent(period_loan_lable, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(period_loan_textField))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 23, Short.MAX_VALUE)
                .addGroup(loan_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(dateChooser_loan, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(data_loan_lable, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(13, 13, 13))
        );

        withDep_cutomer_tabbed.addTab("  Loans  ", loan_panel);

        idcutomer_transform_lable.setFont(new java.awt.Font("Swis721 LtCn BT", 1, 15)); // NOI18N
        idcutomer_transform_lable.setText("ID customer :");

        idcustomer_transform_textfield.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                idcustomer_transform_textfieldActionPerformed(evt);
            }
        });

        idtransportor_transform_lable.setFont(new java.awt.Font("Swis721 LtCn BT", 1, 15)); // NOI18N
        idtransportor_transform_lable.setText("ID transporter :");

        idtransportor_transform_textfield1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                idtransportor_transform_textfield1ActionPerformed(evt);
            }
        });

        money_transform_lable.setFont(new java.awt.Font("Swis721 LtCn BT", 1, 15)); // NOI18N
        money_transform_lable.setText("Amount of money :");

        money_transform_textfield.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                money_transform_textfieldActionPerformed(evt);
            }
        });

        data_transform_lable.setFont(new java.awt.Font("Swis721 LtCn BT", 1, 15)); // NOI18N
        data_transform_lable.setText("The date of the transform :");

        idcutomer_transform_lable1.setFont(new java.awt.Font("Swis721 LtCn BT", 1, 15)); // NOI18N
        idcutomer_transform_lable1.setText("The name of the bank :");

        name_of_the_bank_radio_group.add(same_bank_tranform_radioButton);
        same_bank_tranform_radioButton.setFont(new java.awt.Font("Swis721 LtCn BT", 1, 13)); // NOI18N
        same_bank_tranform_radioButton.setText("Same bank");
        same_bank_tranform_radioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                same_bank_tranform_radioButtonActionPerformed(evt);
            }
        });

        name_of_the_bank_radio_group.add(another_bank_tranform_radioButton);
        another_bank_tranform_radioButton.setFont(new java.awt.Font("Swis721 LtCn BT", 1, 13)); // NOI18N
        another_bank_tranform_radioButton.setText("Another bank");
        another_bank_tranform_radioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                another_bank_tranform_radioButtonActionPerformed(evt);
            }
        });

        name_ofanother_bank_transform_lable.setFont(new java.awt.Font("Swis721 LtCn BT", 1, 13)); // NOI18N
        name_ofanother_bank_transform_lable.setText(" Enter the name of the bank");
        name_ofanother_bank_transform_lable.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        name_ofanother_bank_transform_textField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                name_ofanother_bank_transform_textFieldActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout tansform_panelLayout = new javax.swing.GroupLayout(tansform_panel);
        tansform_panel.setLayout(tansform_panelLayout);
        tansform_panelLayout.setHorizontalGroup(
            tansform_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tansform_panelLayout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(tansform_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(idtransportor_transform_lable, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(idcutomer_transform_lable, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(money_transform_lable, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(data_transform_lable, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(idcutomer_transform_lable1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(tansform_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(tansform_panelLayout.createSequentialGroup()
                        .addGroup(tansform_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(idcustomer_transform_textfield, javax.swing.GroupLayout.DEFAULT_SIZE, 142, Short.MAX_VALUE)
                            .addComponent(idtransportor_transform_textfield1)
                            .addComponent(money_transform_textfield)
                            .addComponent(dateChooser_transform, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(190, 190, 190))
                    .addGroup(tansform_panelLayout.createSequentialGroup()
                        .addGroup(tansform_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(another_bank_tranform_radioButton)
                            .addComponent(same_bank_tranform_radioButton))
                        .addGap(30, 30, 30)
                        .addGroup(tansform_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(name_ofanother_bank_transform_lable, javax.swing.GroupLayout.DEFAULT_SIZE, 161, Short.MAX_VALUE)
                            .addComponent(name_ofanother_bank_transform_textField))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        tansform_panelLayout.setVerticalGroup(
            tansform_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tansform_panelLayout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addGroup(tansform_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(idcutomer_transform_lable, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(idcustomer_transform_textfield, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(tansform_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(idtransportor_transform_lable, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(idtransportor_transform_textfield1, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(19, 19, 19)
                .addGroup(tansform_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(money_transform_lable, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(money_transform_textfield, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(tansform_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(dateChooser_transform, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(data_transform_lable, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(tansform_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(tansform_panelLayout.createSequentialGroup()
                        .addGroup(tansform_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(idcutomer_transform_lable1, javax.swing.GroupLayout.DEFAULT_SIZE, 38, Short.MAX_VALUE)
                            .addComponent(same_bank_tranform_radioButton))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(another_bank_tranform_radioButton)
                        .addGap(86, 86, 86))
                    .addGroup(tansform_panelLayout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addComponent(name_ofanother_bank_transform_lable, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(name_ofanother_bank_transform_textField, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        withDep_cutomer_tabbed.addTab("  Transforming  ", tansform_panel);

        idcustomer_visit_lable.setFont(new java.awt.Font("Swis721 LtEx BT", 0, 14)); // NOI18N
        idcustomer_visit_lable.setText("ID customer :");

        idcustomer_visit_textfield.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                idcustomer_visit_textfieldActionPerformed(evt);
            }
        });

        pass_withdepCustomer_lable1.setFont(new java.awt.Font("Swis721 LtEx BT", 0, 14)); // NOI18N
        pass_withdepCustomer_lable1.setText("Password :");

        pass_withdepCustomer_Password1.setFont(new java.awt.Font("Swis721 LtCn BT", 0, 14)); // NOI18N
        pass_withdepCustomer_Password1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pass_withdepCustomer_Password1ActionPerformed(evt);
            }
        });

        visit_radio_group.add(withdrow_deposit_visit_radio);
        withdrow_deposit_visit_radio.setFont(new java.awt.Font("Swis721 LtCn BT", 1, 13)); // NOI18N
        withdrow_deposit_visit_radio.setText("withdraw or deposit");
        withdrow_deposit_visit_radio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                withdrow_deposit_visit_radioActionPerformed(evt);
            }
        });

        visit_radio_group.add(loans_payment_radio);
        loans_payment_radio.setFont(new java.awt.Font("Swis721 LtCn BT", 1, 13)); // NOI18N
        loans_payment_radio.setText("loans payment");
        loans_payment_radio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loans_payment_radioActionPerformed(evt);
            }
        });

        visit_radio_group.add(total_money_visit_radio);
        total_money_visit_radio.setFont(new java.awt.Font("Swis721 LtCn BT", 1, 13)); // NOI18N
        total_money_visit_radio.setText("total money");
        total_money_visit_radio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                total_money_visit_radioActionPerformed(evt);
            }
        });

        with_depo_visit_table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "amount_of_money", "wit/dep", "date_of_operation", "from_whome", "name_of_banke"
            }
        ));
        jScrollPane1.setViewportView(with_depo_visit_table);

        loans_payment_visit_table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "amount_of_money", "date_of_pay"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.Object.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane2.setViewportView(loans_payment_visit_table);
        if (loans_payment_visit_table.getColumnModel().getColumnCount() > 0) {
            loans_payment_visit_table.getColumnModel().getColumn(1).setHeaderValue("date_of_pay");
        }

        jButton1.setFont(new java.awt.Font("Swis721 LtCn BT", 1, 14)); // NOI18N
        jButton1.setText("Show");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        total_money_visit_table1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "total_money"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane3.setViewportView(total_money_visit_table1);

        fromdate_visit_lable.setText("From :");

        todate_visit_lable.setText("To :");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(idcustomer_visit_lable, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(idcustomer_visit_textfield, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(pass_withdepCustomer_lable1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(pass_withdepCustomer_Password1, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(withdrow_deposit_visit_radio)
                                .addGap(30, 30, 30)
                                .addComponent(loans_payment_radio)
                                .addGap(18, 18, 18)
                                .addComponent(total_money_visit_radio))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(19, 19, 19)
                                .addComponent(fromdate_visit_lable, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(fromdate_visit_dateChooser, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(todate_visit_lable, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(2, 2, 2)
                                .addComponent(todate_visit_dateChooser, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(89, 89, 89))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(56, 56, 56)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 541, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(idcustomer_visit_lable, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(idcustomer_visit_textfield, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pass_withdepCustomer_lable1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pass_withdepCustomer_Password1, javax.swing.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(loans_payment_radio)
                            .addComponent(withdrow_deposit_visit_radio)
                            .addComponent(total_money_visit_radio))
                        .addGap(19, 19, 19)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(fromdate_visit_lable, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(fromdate_visit_dateChooser, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(todate_visit_lable, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(todate_visit_dateChooser, javax.swing.GroupLayout.DEFAULT_SIZE, 27, Short.MAX_VALUE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(11, 11, 11)))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        withDep_cutomer_tabbed.addTab("Visit", jPanel1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(withDep_cutomer_tabbed, javax.swing.GroupLayout.PREFERRED_SIZE, 546, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(withDep_cutomer_tabbed)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void idcustomer_withdepCutomer_textfieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_idcustomer_withdepCutomer_textfieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_idcustomer_withdepCutomer_textfieldActionPerformed

    private void withdep_withdepCustomer_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_withdep_withdepCustomer_buttonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_withdep_withdepCustomer_buttonActionPerformed

    private void withdepo_withdepCustomer_textfieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_withdepo_withdepCustomer_textfieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_withdepo_withdepCustomer_textfieldActionPerformed

    private void withd_withdepCustomer_radioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_withd_withdepCustomer_radioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_withd_withdepCustomer_radioActionPerformed

    private void pass_withdepCustomer_PasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pass_withdepCustomer_PasswordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pass_withdepCustomer_PasswordActionPerformed

    private void id_loan_textfieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_id_loan_textfieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_id_loan_textfieldActionPerformed

    private void pass_loan_PasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pass_loan_PasswordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pass_loan_PasswordActionPerformed

    private void idG1_loan_textfieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_idG1_loan_textfieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_idG1_loan_textfieldActionPerformed

    private void idG2_loan_textfieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_idG2_loan_textfieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_idG2_loan_textfieldActionPerformed

    private void idG3_loan_textfieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_idG3_loan_textfieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_idG3_loan_textfieldActionPerformed

    private void money_loan_textfieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_money_loan_textfieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_money_loan_textfieldActionPerformed

    private void period_loan_textFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_period_loan_textFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_period_loan_textFieldActionPerformed

    private void period_loan_comboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_period_loan_comboBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_period_loan_comboBoxActionPerformed

    private void idcustomer_transform_textfieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_idcustomer_transform_textfieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_idcustomer_transform_textfieldActionPerformed

    private void idtransportor_transform_textfield1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_idtransportor_transform_textfield1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_idtransportor_transform_textfield1ActionPerformed

    private void money_transform_textfieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_money_transform_textfieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_money_transform_textfieldActionPerformed

    private void same_bank_tranform_radioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_same_bank_tranform_radioButtonActionPerformed
        if (same_bank_tranform_radioButton.isSelected()) {
            name_ofanother_bank_transform_lable.setVisible(false);
            name_ofanother_bank_transform_textField.setVisible(false);
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_same_bank_tranform_radioButtonActionPerformed

    private void another_bank_tranform_radioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_another_bank_tranform_radioButtonActionPerformed

        if (another_bank_tranform_radioButton.isSelected()) {
            name_ofanother_bank_transform_lable.setVisible(true);
            name_ofanother_bank_transform_textField.setVisible(true);
        }

        // TODO add your handling code here:
    }//GEN-LAST:event_another_bank_tranform_radioButtonActionPerformed

    private void name_ofanother_bank_transform_textFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_name_ofanother_bank_transform_textFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_name_ofanother_bank_transform_textFieldActionPerformed

    private void idcustomer_visit_textfieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_idcustomer_visit_textfieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_idcustomer_visit_textfieldActionPerformed

    private void pass_withdepCustomer_Password1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pass_withdepCustomer_Password1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pass_withdepCustomer_Password1ActionPerformed

    private void loans_payment_radioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loans_payment_radioActionPerformed

        if (loans_payment_radio.isSelected()) {
            todate_visit_dateChooser.setVisible(true);
            fromdate_visit_dateChooser.setVisible(true);
            todate_visit_lable.setVisible(true);
            fromdate_visit_lable.setVisible(true);
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_loans_payment_radioActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void withdrow_deposit_visit_radioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_withdrow_deposit_visit_radioActionPerformed

        if (withdrow_deposit_visit_radio.isSelected()) {
            todate_visit_dateChooser.setVisible(true);
            fromdate_visit_dateChooser.setVisible(true);
            todate_visit_lable.setVisible(true);
            fromdate_visit_lable.setVisible(true);
        }

        // TODO add your handling code here:
    }//GEN-LAST:event_withdrow_deposit_visit_radioActionPerformed

    private void total_money_visit_radioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_total_money_visit_radioActionPerformed

        if (total_money_visit_radio.isSelected()) {
            todate_visit_dateChooser.setVisible(false);
            fromdate_visit_dateChooser.setVisible(false);
            todate_visit_lable.setVisible(false);
            fromdate_visit_lable.setVisible(false);
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_total_money_visit_radioActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Custumer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Custumer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Custumer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Custumer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Custumer().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton another_bank_tranform_radioButton;
    private javax.swing.JLabel data_loan_lable;
    private javax.swing.JLabel data_transform_lable;
    private com.toedter.calendar.JDateChooser dateChooser_loan;
    private com.toedter.calendar.JDateChooser dateChooser_transform;
    private com.toedter.calendar.JDateChooser dateChooser_withdepCustomer;
    private javax.swing.JLabel date_withdepCustomer_lable;
    private javax.swing.JRadioButton depo_withdepCustomer_radio;
    private com.toedter.calendar.JDateChooser fromdate_visit_dateChooser;
    private javax.swing.JLabel fromdate_visit_lable;
    private javax.swing.JLabel idG1_loan_lable;
    private javax.swing.JTextField idG1_loan_textfield;
    private javax.swing.JLabel idG2_loan_lable;
    private javax.swing.JTextField idG2_loan_textfield;
    private javax.swing.JLabel idG3_loan_lable;
    private javax.swing.JTextField idG3_loan_textfield;
    private javax.swing.JTextField id_loan_textfield;
    private javax.swing.JTextField idcustomer_transform_textfield;
    private javax.swing.JLabel idcustomer_visit_lable;
    private javax.swing.JTextField idcustomer_visit_textfield;
    private javax.swing.JLabel idcustomer_withdepCutomer_lable;
    private javax.swing.JTextField idcustomer_withdepCutomer_textfield;
    private javax.swing.JLabel idcutomer_loan_lable;
    private javax.swing.JLabel idcutomer_transform_lable;
    private javax.swing.JLabel idcutomer_transform_lable1;
    private javax.swing.JLabel idtransportor_transform_lable;
    private javax.swing.JTextField idtransportor_transform_textfield1;
    private javax.swing.JButton jButton1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JPanel loan_panel;
    private javax.swing.JRadioButton loans_payment_radio;
    private javax.swing.JTable loans_payment_visit_table;
    private javax.swing.JLabel money_loan_lable;
    private javax.swing.JTextField money_loan_textfield;
    private javax.swing.JLabel money_transform_lable;
    private javax.swing.JTextField money_transform_textfield;
    private javax.swing.JLabel money_withdepCustomer_label;
    private javax.swing.JLabel money_withdepCustomer_lable;
    private javax.swing.ButtonGroup name_of_the_bank_radio_group;
    private javax.swing.JLabel name_ofanother_bank_transform_lable;
    private javax.swing.JTextField name_ofanother_bank_transform_textField;
    private javax.swing.JLabel newmoney_withdepCustomer_label;
    private javax.swing.JLabel newmoney_withdepCustomer_lable;
    private javax.swing.JPasswordField pass_loan_Password;
    private javax.swing.JLabel pass_loan_lable;
    private javax.swing.JPasswordField pass_withdepCustomer_Password;
    private javax.swing.JPasswordField pass_withdepCustomer_Password1;
    private javax.swing.JLabel pass_withdepCustomer_lable;
    private javax.swing.JLabel pass_withdepCustomer_lable1;
    private javax.swing.JComboBox<String> period_loan_comboBox;
    private javax.swing.JLabel period_loan_lable;
    private javax.swing.JTextField period_loan_textField;
    private javax.swing.JRadioButton same_bank_tranform_radioButton;
    private javax.swing.JPanel tansform_panel;
    private com.toedter.calendar.JDateChooser todate_visit_dateChooser;
    private javax.swing.JLabel todate_visit_lable;
    private javax.swing.JRadioButton total_money_visit_radio;
    private javax.swing.JTable total_money_visit_table1;
    private javax.swing.ButtonGroup visit_radio_group;
    private javax.swing.JLabel widdepo_withdepCustomer_label;
    private javax.swing.JTabbedPane withDep_cutomer_tabbed;
    private javax.swing.ButtonGroup with_depo_radio_group;
    private javax.swing.JTable with_depo_visit_table;
    private javax.swing.JRadioButton withd_withdepCustomer_radio;
    private javax.swing.JButton withdep_withdepCustomer_button;
    private javax.swing.JTextField withdepo_withdepCustomer_textfield;
    private javax.swing.JPanel withdraw_depo_panel;
    private javax.swing.JRadioButton withdrow_deposit_visit_radio;
    // End of variables declaration//GEN-END:variables
}
